# GitHub Actions workflow: 自动在多个平台上构建可执行文件
name: Build Multi-Platform
permissions:
  contents: write  # 允许创建和更新 release
  packages: write  # 允许管理发布包
  actions: read    # 允许读取 Actions 元数据

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      VERSION: 0.1
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --noconfirm --onefile --windowed main.py

      - name: Rename executable
        run: |
          if [ "${RUNNER_OS}" == "Windows" ]; then ext=".exe"; else ext=""; fi
          mv dist/main${ext} dist/chat-log-cleaner_${{ env.VERSION }}${ext}
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chat-log-cleaner-${{ matrix.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create GitHub Release and upload assets
        uses: ncipollo/release-action@v1
        with:
          tag: v0.1
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: artifacts/**
